### ISSUE TITLE
Add 'Cancel' button on retry dialog

### ISSUE THREAD

**Issue by deszip** [Citadel-sh/BugTracker#2]
### Fuze version? (Ex. Fuze 0.1.0a)
Fuze 0.1.2 (1)

### macOS Version? (Ex. mac 10.15)
10.15.3 (19D76)

### Steps to reproduce 
Run the app

### Expected behavior
Sync modal dialog has 'cancel' button to dismiss it, so 'close' button became available.
The only way to close Fuze now is to kill process :)

### Screenshots (optional)
<img width="672" alt="Снимок экрана 2020-03-22 в 19 27 22" src="https://user-images.githubusercontent.com/432462/77255989-13a7ed80-6c74-11ea-853c-2d3e59a13b46.png">

**Comment by Eastkap** [comment]
Not only this, but my iPhone never appears to be found also

**Comment by klmitchell2** [comment]
Hey @Eastkap, @deszip 

Which version of python are you using? Also, where is your location of your Frida CLI tools (i.e, `frida-ps`, `frida`, `frida-ls-devices`)?

**Comment by Eastkap** [comment]
Py version : 3.7.3
All frida utils are in is in : /usr/local/anaconda3/bin/*

**Comment by Eastkap** [comment]
@klmitchell2 I've fixed it by creating symbolic links of the Frida CLI tools to `/usr/local/bin`

**Comment by Eastkap** [comment]
![image](https://user-images.githubusercontent.com/2210144/77626349-826f9a00-6f45-11ea-9c13-08dd9fc42149.png)
Now I'm getting this all the time

**Comment by klmitchell2** [comment]
@Eastkap glad that the symbolic link worked. Unfortunately it looks like you are receiving a general error that we are unable to parse. 

We are hoping to have a release soon that will give us better insight into what causes these errors. The info you have provided (especially being able to symbolically link `frida-tools`) is really helpful. 

I'm sorry that we do not have an answer to fix this issue right now. Hoping we can address this in the near future.

**Comment by Adikesha** [comment]
Not working for me either. Keeps getting the same error.
![Screen Shot 2020-03-27 at 1 25 00 PM](https://user-images.githubusercontent.com/2342448/77797575-8b886600-702e-11ea-86f5-2aa4bfa1c87f.png)

Tried reattaching device several times. Still not working.

**Comment by colealanroberts** [comment]
@Adikesha @Eastkap @deszip
This isn't likely a fix for your problem, but it will give us better insight into how we might fix the issue.

Can you visit https://getfuze.app/downloads/alpha and try again?

**Comment by colealanroberts** [comment]
@Adikesha @Eastkap @deszip We're pretty confident that version 0.1.3 will fix these issues. Can you please download the latest alpha from https://getfuze.app/downloads/alpha. Also, we have noticed that sometimes the UI will hang during the first launch of the new version. Can you let us know if that's the case? Thanks!

**Comment by deszip** [comment]
Tried v0.1.3, finds the device and shows apps list (Icons are missing in grid view btw). On decrypting it fails:

<img width="342" alt="Снимок экрана 2020-05-02 в 11 54 12" src="https://user-images.githubusercontent.com/432462/80859760-da4ba000-8c6b-11ea-982c-b80783437bbd.png">

I didn't find anything helpful in output.
Maybe I can enable some debug mode to give you logs?

Another minor thing is a password dialog. If you mistype password and left 'remember' checkbox there is no way to reset it. Had to reinstall the app.
Also would be great to preserve checkbox state, so if I've unchecked it - it stays unchecked on next launch.

**Comment by colealanroberts** [comment]
@deszip Is your device jail broken? The only times I’ve seen missing icons is when using a nonJB device.

The password prompt should reappear if the password is incorrect but you may be receiving that error earlier in the process so it’s likely it never reappears. You can reset it under Preferences > Advanced > Reset.

**Comment by deszip** [comment]
Sure it's jailbroken, it's Electra and I use it to decrypt apps all the time.
Do you have plans to opensource Fuze?

**Comment by colealanroberts** [comment]
@deszip as of right now, no. We don’t have plans to make the source available.

**Comment by klmitchell2** [comment]
@deszip, could you provide a screen shot of the apps thats are listed? Additionally, when you attempt to decrypt the app, does the app ever spawn on your device? 

Also, thanks for the feedback and help.

**Comment by deszip** [comment]
No app doesn't start on device.
<img width="1275" alt="Снимок экрана 2020-05-02 в 22 42 05" src="https://user-images.githubusercontent.com/432462/80885645-49ee7900-8cc6-11ea-8eee-dafb2d279045.png">

> Also, thanks for the feedback and help.
Glad to help

**Comment by klmitchell2** [comment]
Thanks for that screenshot. 

What version of Frida are you using on your device? 

I'm using Frida for pre-A12 devices (v12.8.20)
![IMG_8338BC0D4D2A-1](https://user-images.githubusercontent.com/5108164/80890904-1429a000-8c86-11ea-9f1a-33ff079ced78.jpeg)

**Comment by deszip** [comment]
Ok I have a small progress, after reinstalling frida on both the device and mac I got the icons :)
<img width="1054" alt="Снимок экрана 2020-05-03 в 11 12 12" src="https://user-images.githubusercontent.com/432462/80910102-eef46a80-8d35-11ea-8478-d47f31f24820.png">

But still the same error on decrypt.

I have the same version of Frida (12.8.20) installed from their official repo.

![IMG_F033749BAA79-1](https://user-images.githubusercontent.com/432462/80910160-48f53000-8d36-11ea-9300-5f9162d4732e.jpeg)

And looks like its working:
```
Location: ~ frida-ls-devices
Id                                        Type    Name
----------------------------------------  ------  ------------
local                                     local   Local System
005fb0e1d848b1b302e6d9491d9de7219d8244de  usb     iPhone
tcp                                       remote  Local TCP
Location: ~ frida-ps -Uai | grep -i cydia
1408  Cydia          com.saurik.Cydia
   -  Extender       com.cydia.Extender
```

I think more verbose error reporting would help.
Maybe you can add a flag to defaults and trigger verbose logging based on it?
Users can enable it with smth like:
```
defaults write com.citadel.Fuze ExtendedLoggingFlagName -bool YES
```

**Comment by colealanroberts** [comment]
Marking as closed.
